[package]
name = "networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanomsg = "0.7.2"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"]}
